name: parkeasy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_auth: ^5.1.3
  dartz: ^0.10.1
  cloud_firestore: ^5.2.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  firebase_app_check: ^0.3.0+4
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lang/en.json
    - assets/lang/fr.json
    - assets/lang/ar.json
    - assets/dark_map_style.json
    - assets/light_map_style.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
